---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: dev
spec:
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - env:
        - name: APP_URL
          valueFrom:
            secretKeyRef:
              key: app-url
              name: mariadb-secrets
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: db-host
              name: mariadb-secrets
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              key: db-database
              name: mariadb-secrets
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: db-user
              name: mariadb-secrets
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: mariadb-secrets
        image: buffyxo/laravel:dev
        name: laravel
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 200Mi
